- src/routes/installation/sc.svx
- open platform extensions directly in SC
- add steps for dequarantining .scx
> update sc installation instructions

- src/routes/installation/pd.svx
Typo and naming fixes in Pd install blurb
> Correct PureData to Pure Data, and Max to Pure Data

- src/lib/components/Audio.svelte
This adds a component for inserting mp3 audio into documents. It will soon be supplanted by something more robust that uses peak.js to make itmore interactive and easy to visually grasp what the sound is.﻿
> Audio Component

- src/lib/components/Crumbs.svelte
- src/lib/components/TOC.svelte
- src/routes/__layout.svelte
Adds a table of contents to pages for any main headings (h2)
> Table of contents

- src/app.scss
- src/lib/Header.svelte
- src/lib/components/Crumbs.svelte
- src/lib/components/TOC.svelte
- src/routes/__layout.svelte
Fix horrendous layout of table of contents on sizes close to the foldover﻿
> toc layout fix

- src/lib/widget/KDTree.svelte
- src/routes/reference/kdtree.svx
This adds radius searching to the KDTree example.﻿
> kdtree radius demo

- src/lib/components/Button.svelte
- src/lib/widget/KDTree.svelte
Move the fit button to the top and make it disable once it has been fitted once.﻿
> KDTree UI Enhancement

- src/lib/components/DataSetView.svelte
This proposes a component for viewing datasets from .json static assets﻿
> [feature] DataSet Viewer

- src/lib/components/Flair.svelte
Adds support for an event flair﻿
> Add event flair

- scripts/metadata.js
- src/routes/__layout.svelte
- src/routes/madewithflucoma/index.svx
- src/routes/madewithflucoma/reactive-flows.svx
- ensure the surrounding <a> expands to the width of central column
- override any crumbs with a custom crumb attribute
- give more width to the sides in | | | format
- add crumb for reactive flows
> Update reactive flows structure

- src/lib/components/MFWHeader.svelte
- src/lib/components/TOC.svelte
- make the table of contents sit relative / fixed depending on layout
- remove transition from madewithflucoma template
> Update table of contents layout

- src/lib/widget/KDTree.svelte
- src/routes/reference/kdtree.svx
- update kdtree text
- remove unneeded variable
- paint circle onto real mouse coords
- improve widget
- update text
> [Review Changes] KDTree

- src/lib/widget/ChromaDemo.svelte
- src/routes/reference/chroma.svx
- update text with suggestions
- make buffer (window) larger to accomodate low frequency bass sounds
> [Review Changes] Chroma

- src/routes/overviews/2d-corpus-explorer.svx
- src/routes/overviews/classification-neural-network.svx
- src/routes/overviews/regression-neural-network.svx
This adds an overview entry for all the tutorials so far.
This means they get added to the searchable index and can be accessed and found more easily in situ with the docs and refs here.﻿
> [Content] Tutorial Entries

- src/lib/components/Flair.svelte
> [Enhance] Tutorial Flair

- src/app.css
- src/lib/Header.svelte
- src/lib/components/Crumbs.svelte
- src/lib/components/Image.svelte
- src/lib/components/Search.svelte
- src/lib/components/TOC.svelte
- src/utils.css
Many components use a ludicrous amount of <div> where semantic elements might be more useful and helpful to screen readers and other accessibility content. This PR aims to address those faults and fix them.﻿
> [Enhance] Semantic HTML adjustments

- src/lib/components/IndentNote.svelte
This makes the indented note component more usable and pretty.
It should be useful for adding socratic thoughts throughout overvies and references
> [Enhance] Indent Note Component

- src/app.html
- src/lib/components/ArrowRight.svelte
- src/lib/components/LandingCard.svelte
- src/routes/index.svx
- add landing card cmponent
- make the base target a blank page for external links
- style the landing card
- add an svg for arrow right
- update main index page with new landing cards
> [Enhance] Front page layout

- src/lib/components/ResourceLink.svelte
- src/routes/reference/chroma.svx
Adds a component for reliably rendering out resources (usually at the bottom of articles).
> [Enhance] Resource Links

- src/routes/madewithflucoma/hayes.svx
- src/routes/madewithflucoma/pasquet.svx
- add a pointer for pasquet patches
- add pointer note for hayes patches
> [Enhance] Use IndentNote for patch links

- src/routes/madewithflucoma/hayes.svx
There was a typo i wanted to fix though..
> [Content] Typo correction

- src/routes/reference/umap.svx
Adds several related resources to UMAP reference that I rely on in the next plotting video.﻿
> [Content] UMAP Related Resources

- scripts/git.js
When the git log is parsed for each file if nothing is returned it should just provide some dummy data.﻿
> [Fix] Git Parsing

- src/routes/reference/index.svelte
This adds a search bar to the references bar which uses fuzzy lookup against the title, category, tags and blurb. Seems to do the trick in not being too restrictive.
> [Enhance] Add Search to references

- src/lib/components/DataSetView.svelte
- src/lib/components/LabelSetView.svelte
- src/routes/reference/labelset.svx
> [Content] LabelSet Reference

- src/lib/app.js
Makes installation steps show up in search.﻿
> [Enhance] Installation in search

- src/lib/components/Search.svelte
This solves many weird issues with search such as hovering focus and pressing enter performing navigation that was bogus.﻿
> [Enhance] Bad search behaviours removed

- src/lib/components/Crumbs.svelte
- src/lib/components/Spectroscope.svelte
- src/lib/components/reference/Search.svelte
- src/lib/widget/Ampslice.svelte
- src/lib/widget/NoveltyCurve.svelte
- src/lib/widget/OnsetSlice.svelte
- src/routes/npy-parsing.svelte
- tsconfig.json
- remove console.log everywhere its not needed
- cleanup tsconfig while we are here
> [Fix] Various Maintenance Tasks

- scripts/related.js
Adds backreferences to the related tree graph.﻿
> [Enhance] Backreferences

- src/lib/widget/BufFlatten.svelte
Fix various bugs with BufFlatten, namely with form validation and entering bogus values for the Svelte HTML iterators.﻿
> [Fix] BufFlatten Bugs

- src/routes/installation/max.svx
- src/routes/installation/pd.svx
- src/routes/installation/sc.svx
- update pd instructions
- update max and sc too
Also fixed a bunch of layout issues which went unnoticed from the layout refactor.
> [Fix] Installation Instructions

- src/routes/installation/max.svx
Some tabs had content that was justified due to *hand waving*.
I've fixed that now﻿
> [Fix] Fix justified layouts in some tabs

- src/lib/components/PopoverNav.svelte
Adds a few additional acknowledgements, recognising special contribution to the learn platform.﻿
> Additional acknowledgements

- src/routes/reference/bufnmfseed.svx
See https://github.com/flucoma/flucoma-core/pull/173
> BufNNDSVD -> BufNMFSeed

- src/routes/reference/kmeans.svx
- src/routes/reference/skmeans.svx
This is an attempt to point and not confuse people at the distance metrics of kmeans in skmeans. it links with the docs PR.
> skmeans amendment

- src/lib/Header.svelte
- src/lib/components/PopoverNav.svelte
- src/lib/components/Search.svelte
- src/routes/installation/max.svx
- src/routes/installation/pd.svx
- src/routes/installation/sc.svx
- larger more fluffy header
- make search less donuty
- update the installation instructions
> [enhance] header improvements + installation instructions

- .prettierignore
- .prettierrc
- package.json
- src/lib/app.js
- src/lib/components/Audio.svelte
- src/lib/components/AuthorTag.svelte
- src/lib/components/ResourceLink.svelte
- src/lib/components/Search.svelte
- src/lib/components/Slider.svelte
- src/lib/components/mosaic/RefCategory.svelte
- src/lib/widget/BufScale.svelte
- src/lib/widget/KDTree.svelte
Modifies the global search to use fuse.js for fuzzy searching. It is a bit more flexible in that document searching can be weighted, meaning we can de-emphasise the content of the blurb in the search which was often confusing results.
> [enhance] fuse.js for fuzzy searching

- src/routes/learn/classification-neural-network/+page.svx
- src/routes/learn/regression-neural-network/+page.svx
Fixed issue https://github.com/flucoma/learn-website/issues/396
> Fix URL for "Classifying Sounds with a Neural Network in Max" and "Controlling a Synth using a Neural Network in Max"

- src/routes/reference/knnregressor/+page.svx
tidy up the reference changes for the PR on core
> modified the learn entry on knnregressor, now multioutput

- src/app.css
- src/lib/components/YouTubeChapters.svelte
- src/lib/layouts/Content.svelte
- src/routes/+layout.svelte
- src/routes/explore/gioti/+page.svx
- src/routes/explore/rss/+server.js
This adds RSS syndication by providing a server endpoint that aggregates podcast markdown and its associated metadata into the RSS XML format.
- add rss endpoint for explore
- correct gborn typo
- make the wrapper a div and the content a main
- make flairs contrast better with background
- update YouTube chapters styling for RSS
> RSS Syndication for Explore Podcasts

- static/examples/2d-plot/plotter-6.maxpat
Added the patch for plotter tutorial 6 next to the first 5 tutorial patches
> added plotter 6 tutorial patch

- src/routes/(content)/learn/weighting-stats/+page.svx
- **use node version 18**
- **include Admonition component**
> Include missing Admonition import
