flucoma/learn-website

- .gitignore
- scripts/extract_structure.py
- src/lib/app.js
- src/lib/components/EditHistory.svelte
- src/lib/components/HR.svelte
- src/lib/layouts/overviews.svelte
- src/lib/layouts/reference.svelte
This adds edit history to each page derived from the `extract_stucture.py` script.
It also provides a link to edit the file directory on github, as well as to see who last changed them and when.
> edit history

- scripts/db.js
- src/lib/app.js
- src/lib/components/CardList.svelte
- src/lib/components/Flair.svelte
- src/routes/madewithflucoma/index.svx
- src/routes/overviews/index.svx
Adds flair support for the cards that appear in main sections. This necessitated an overhaul _anyway_ of how these cards are drawn as a template which makes the code not only smaller but easier to follow and extend.
> Improved integration of flairs onto content

- README.md
- src/lib/components/Crumbs.svelte
- src/lib/components/EditHistory.svelte
- src/lib/components/TOC.svelte
- src/routes/search/[query].svelte
- use $page.url.pathname
- use param object in dynamic route (api update)
Various small changes will eventually break the site, so I'm updating them now to get ahead of the game. This mainly refers to how the $page object was changed in [208](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next208) onwards.
> Update to new SvelteKit API

- src/lib/layouts/madewithflucoma.svelte
- src/lib/layouts/overviews.svelte
The tags are currently not very useful and won't be till a full document search is implemented.
As such, this PR removes them from the layouts for now.﻿
> [Enhance] Remove tags from view of articles

- src/app.css
- src/lib/Header.svelte
Only using overpass is not only ugly, it might not render properly. For most of the content we should use the system sans-serif font.﻿
> [Enhance] Neutral Content Fonts

- package.json
- src/app.css
- svelte.config.js
Adds auto-link-headings to the build process to inject an <a> before each heading with a corresponding `id`.
> [Enhance] Auto-link headings

- package.json
- scripts/metadata.js
Instead of rolling my own link cleanser, I've leveraged the same one that the [rehype plugin](https://github.com/rehypejs/rehype-slug) uses under the hood. This ensures parity.
> [Enhance] GitHub style slugs

- .gitignore
- package.json
- scripts/related.js
- src/lib/components/Related.svelte
- src/lib/components/TOC.svelte
- src/lib/widget/BufScale.svelte
- src/routes/__layout.svelte
This adds a "related" section under the table of contents. It basically pulls any internal links out of the document at build time and then creates a small json bundle that can be accessed client side. 
My questions are, is this useful? How can we make it even more useful? I imagine `seealso` can become a part of this when we eventually get the DOCS producing raw JSON.
> [Enhance] Related articles under table of contents

- src/routes/__error.svelte
Adds an `__error.svelte` to make bad routes look less bad.﻿
> [Enhance] Error Page

- src/lib/components/Image.svelte
Allows you to use markdown format in Image labels:
```sv
<Image
src="/reference/hpss/03_median_filter_on_a_row.png"
label="[hello](https://google.com) One row (FFT bin) of the spectrogram. x axis = time; y axis = magnitudes; median filter length = 51"
/>
```﻿
> [Enhance] Markdown Label Format

- static/examples/2d-plot/plotter-2.maxpat
- static/examples/2d-plot/plotter-3.maxpat
- static/examples/2d-plot/plotter-4.maxpat
- static/examples/2d-plot/plotter-5.maxpat
https://github.com/flucoma/fluid.waveform/issues/20#event-6363018465
At one point I removed numerical references in waveform because they were potentially confusing. This breaks these patches which are now fixed.
> [Fix] Numerical References in Waveform

- src/lib/components/Search.svelte
Handlers for key presses were happening globally, rather than when the search bar was focused. This means the user could invisibly navigate up and down the list of entries, and actually navigate away from the page when when the search drop down was not preset.﻿
> [Fix] Search Focus Specificity

- package.json
Various issues have cropped up in next, so this pins the svelte version to 321.﻿
> [Fix] Pin sveltekit version to 321

- scripts/related.js
`Set` uses `SameValueZero` which checks by reference, rather than by value for equality meaning duplicate related links appeared at the top of articles. Now uses lodash `_.isEqual` to check for equality.﻿
> [Fix] Duplicate Related Links

- package.json
- src/lib/widget/KMeans.svelte
We were previously using https://www.npmjs.com/package/tf-kmeans for the KMeans algorithm explanation.
It is seemingly unmaintained and had some dependency issues so I forked it and made it work with our code.
> [Fix] Use FluCoMa kmeans package

- scripts/related.js
Fixes situations where you want to use # in a link to go to an anchor.
> [Fix] Related links parsing with #

- src/routes/installation/pd/+page.svx
I met with some confused Pure Data users today (including some advanced users) who said that the installation instructions were unclear. I updated them to be more descriptive of the steps needed to install FluCoMa for Pure Data.
> added to pure data installation instructions

- src/routes/(content)/getting-started/+page.svelte
after a few users complained they couldn't find a link to installations, I tried to add it to the home page of 'getting started'
I strangly cannot use the links at that level, and I wonder why.  help?
> attempt at adding the link

- static/learn/bufnmf/bufnmf-overview-example.maxpat
Turned on `fluid.bufnmf~` resynthmode in the max help file on BufNMF learn page.
> turned on `fluid.bufnmf~` resynthmode in help file

- static/learn/distribution/distribution-checking-max.maxpat
Fixed a bug in the max patch on the Distributions and Histograms page. Step2 was using the wrong output of fluid.normalize.
> bug fix in distribution max patch

- src/routes/(content)/reference/mfcc/DropZero.svelte
MFCC reference page's drop zero example has the "startCoeff = 0" and "startCoeff = 1" buttons the wrong way round, they do the opposite of what they say.
> Fix MFCC ref page "Drop Zero" buttons wrong way round

- src/routes/(content)/reference/mfcc/DropZero.svelte
MFCC reference page's drop zero example doesn't start analyser with audio playback after the first time it's paused, requiring a page refresh. Seems like the `analyser.start();` line is simply placed one curly bracket too early.
> Fix MFCC ref page "Drop Zero" analyser not always starting with audio playback

- .github/workflows/deploy.yml
- .github/workflows/pr.yml
Many packages are still capped at version 18 of node. This downgrades the deployment environments to 18.
> Downgrade node versions to 18

- src/lib/components/front-page/WelcomeBanner.svelte
- src/lib/components/podcasts/Hero.svelte
adding a return link to the podcast, and reordering the tags of the landing page so they are in the same order as the menu bar
this is a bit crude but the podcast page layout is not the same and there was no way to come back. Ideally it would have the same header than the rest of learn, with all the menus, but I didn't manage to do that...
> navigation to/from the podcast page
